### PR TITLE
Support additional properties

### PR DESCRIPTION
**Pull request by CarstenWickner**
This implements feature request #22 – with the extension of not only catering for `false` to be set as `additionalProperties` but also to define a sub-schema for those `additionalProperties`.

Expected usage for the use-case described in #22 could be something like this (depending on what is being treated as `type: "object"` according to other configurations):
```java
SchemaGeneratorConfigBuilder.forTypesInGeneral()
    .withAdditionalPropertiesResolver(scope ->
        scope.isContainerType()
        || scope.getType().isInstanceOf(Number.class)
        || scope.getType().isInstanceOf(String.class)
        || scope.getType().isPrimitive()
            ? null
            : Void.class);
```
- Providing `null` is reserved for the "neutral" behaviour, i.e. not adding an `additionalProperties` attribute and thereby allowing additional properties of any type to be included in a respective JSON instance.
- Providing `Void.class` or `Void.TYPE` results in `"additionalProperties": false` to be included in the generated JSON Schema.
- Providing any other `Type` (can be a `Class`, `GenericType` or `ResolvedType` – e.g. as created via the `scope.getContext().resolve(mainType, typeAttributes...)`) will result in a corresponding sub-schema to be included, e.g. `"additionalProperties": { "type": "string" }`

@ALEUT what do you reckon? Does that fulfill your requirements?
The part about having to implicitly filter-out non-"object" schemas (where `additionalProperties` wouldn't make any sense) is not too nice, but I'm not sure how properly handle this in a more generic way.

### CODE REVIEW

**Comment by ALEUT** [comment]
Hi @CarstenWickner 
Looks slightly tricky to use (looks it's enough difficult to apply the resolver without an example). What will be for Maps, for which we just have `type: object` and nothing else. It will be object, but shouldn't have "additionalProperties": false.

**Comment by CarstenWickner** [comment]
Hi @ALEUT,
to explicitly allow `additionalProperties`, the resolver would simply have to return `Object.class`.

**Comment by CarstenWickner** [comment]
Merging this as-is, since I believe that already to be a meaningful extension of the library.

Not closing #22 though, since I still got some ideas to make the usage more convenient/intuitive.

**Comment by ALEUT** [comment]
@CarstenWickner could you please show what will be generated for any map? Just `type: object` without `additionalProperties`?

**Comment by CarstenWickner** [comment]
Hi @ALEUT,

You have possibilities:
- simply omitting the `additionalProperties`, or
- specifying the `Map` defined value type as sub-schema.

Please refer to the newly added example in the README for that particular use-case and let me know if that’s not clear enough.

**Pull request merged**
