### PR TITLE
Fix JsonPropertyOrder with child annotations

### PR DESCRIPTION
**Pull request by magicDGS**
I have added a test to demonstrate the issue that was failing before the actual change. The result that was given before the fix was:

```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "type" : "object",
  "properties" : {
    "3_third" : {
      "type" : "integer",
      "description" : "My integer description"
    },
    "1_first" : {
      "type" : "string",
      "description" : "My string description"
    },
    "2_second" : {
      "type" : "string",
      "description" : "My second string description"
    }
  }
}
```

I tried to have a workaround by extending the `JsonPropertySorter` and override the `getPropertyIndex`, but I couldn't access the `propertyOrderPerDeclaringType` on the custom implementation. After checking the rest of the test, I guess that it should not cause any regression.

### CODE REVIEW

**Comment by magicDGS** [comment]
@CarstenWickner  - could it be possible in case that this is approved to cut a new version of the library. I need it to proceed proceed with some implementation on the project where this was found, so I would really appreciate if it is possible. Thanks a lot!

**Review by CarstenWickner — APPROVED** [review]
Thank you for this contribution.
I'll merge this to a feature branch first, to make it a bit more consistent with the existing code (mostly formatting).
I aim to create a new release soon.

**Comment by CarstenWickner** [comment]
Hi @magicDGS,

I've just released this change as [v4.33.1](https://github.com/victools/jsonschema-generator/releases/tag/v4.33.1).
It may take a couple of hours to fully propagate everywhere.

**Comment by magicDGS** [comment]
Thank you very much, @CarstenWickner - both the software and you as maintainer are great for the java ecosystem :relaxed:

**Pull request merged**
